---
#
#
# Parameters:
#   - remove_build_dependencies (bool): false
#   - milvus_version (string): version of milvus to install
#   - etcd_version (string): version of etcd to install
#   - etcd_executable_prefix (string): path to dir under which etcd executables should live.
#   - auto_start (bool): whether to automatically start milvus and it's required services.
#
- name: Prepare Build env
  import_playbook: baremetal/install_build_env.yml
- name: Install Minio
  import_playbook: baremetal/install_minio.yml
- name: Install Etcd
  import_playbook: baremetal/install_etcd.yml
- name: Install Milvus
  import_playbook: baremetal/install_and_run_milvus.yml 
