---
- name: Install Milvus
  hosts: techzone
  tasks:
   - name: Create Temp dir
     ansible.builtin.tempfile:
      state: directory
     register: dload_dir

   - name: Download Milvus Source
     ansible.builtin.git:
      repo: https://github.com/milvus-io/milvus.git
      single_branch: true
      version: v{{ milvus_version }}
      dest: "{{ dload_dir.path }}/milvus"

   - name: Download milvus patch
     ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/ppc64le/build-scripts/master/m/milvus/milvus-v{{ milvus_patch_version }}.patch
      dest: "{{ dload_dir.path }}/milvus.patch"
      mode: u+rw
      owner: "{{ ansible_user }}"

   - name: Apply patch
     ansible.builtin.command:
      cmd: git apply ../milvus.patch
      chdir: "{{ dload_dir.path }}/milvus"

   # NOTE: Apply MCPU not yet supported (was defaulting to false anyways.)
   # Requires milvus_install micromamba environment

   - name: Run Build
     ansible.builtin.shell:
      cmd: micromamba run --root-prefix={{ conda_dir }} -n milvus_install make -j$(nproc)
      chdir: "{{ dload_dir.path }}/milvus"
     register: build_command
     failed_when: false

   - name: Patch rust crates
     when: build_command.rc != 0 
     ansible.builtin.shell: 
      cmd: cargo update -p time
      chdir: "{{ dload_dir.path }}/milvus/internal/core/thirdparty/tantivy/tantivy-binding/"

   - name: Rerun Build
     ansible.builtin.shell:
      # NOTE: This is a quite extensive build process. Increasing memory helps. Running to many cores results in make getting killed
      #       by the OOM killer :).
      cmd: micromamba run --root-prefix={{ conda_dir }} -n milvus_install make -j10
      chdir: "{{ dload_dir.path }}/milvus"
     when: build_command.rc != 0

   - name: Create Milvus directory
     ansible.builtin.file:
      path: "{{ milvus_dir }}"
      state: present
      mode: u=rw,o=r,a=r

   - name: Copy Binaries
     ansible.builtin.copy:
      src: "{{ dlaod_dir.path }}/milvus/bin/"
      dest: "{{ milvus_dir }}/bin/"
      mode: u+x

   - name: Copy Configs
     ansible.builtin.copy:
      src: "{{ dlaod_dir.path }}/milvus/configs/"
      dest: "{{ milvus_dir }}/configs/"
      mode: u+x

   - name: Copy Libraries (64bit)
     ansible.builtin.copy:
      src: "{{ dlaod_dir.path }}/milvus/internal/core/output/lib64/"
      dest: "{{ milvus_dir }}/lib/"
      mode: u+rx

   - name: Copy Libraries
     ansible.builtin.copy:
      src: "{{ dlaod_dir.path }}/milvus/internal/core/output/lib/"
      dest: "{{ milvus_dir }}/lib/"
      mode: u+rx

   - name: Remove Temp dir
     ansible.builtin.file:
      path: "{{ dload_dir.path }}"
      state: absent
