- name: Create temporary directory
  ansible.builtin.tempfile:
    state: 
- name: Download binary
  ansible.builtin.get_url:
    url: "https://dl.min.io/server/minio/release/linux-ppc64le/minio"
    dets: ""